apiVersion: v1
kind: Secret
metadata:
  name: cnam-registry-credentials 
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: >-
    {
      "auths": {
        "https://index.docker.io/v1/":{
            "username":"synapsety",
            "password":"Nathalies1",
            "email":"gregoryhuot4@gmail.com",
            "auth":"c3luYXBzZXR5Ok5hdGhhbGllczE="
        },
        "https://index.docker.io/v2/":{
            "username":"synapsety",
            "password":"Nathalies1",
            "email":"gregoryhuot4@gmail.com",
            "auth":"c3luYXBzZXR5Ok5hdGhhbGllczE="
        },
        "auth.docker.io":{
            "username":"synapsety",
            "password":"Nathalies1",
            "email":"gregoryhuot4@gmail.com",
            "auth":"c3luYXBzZXR5Ok5hdGhhbGllczE="
        },
        "registry.docker.io":{
            "username":"synapsety",
            "password":"Nathalies1",
            "email":"gregoryhuot4@gmail.com",
            "auth":"c3luYXBzZXR5Ok5hdGhhbGllczE="
        },
        "docker.io":{
            "username":"synapsety",
            "password":"Nathalies1",
            "email":"gregoryhuot4@gmail.com",
            "auth":"c3luYXBzZXR5Ok5hdGhhbGllczE="
        },
        "https://registry-1.docker.io/v2/": {
            "username":"synapsety",
            "password":"Nathalies1",
            "email":"gregoryhuot4@gmail.com",
            "auth":"c3luYXBzZXR5Ok5hdGhhbGllczE="
        },
        "registry-1.docker.io/v2/": {
            "username":"synapsety",
            "password":"Nathalies1",
            "email":"gregoryhuot4@gmail.com",
            "auth":"c3luYXBzZXR5Ok5hdGhhbGllczE="
        },
        "registry-1.docker.io": {
            "username":"synapsety",
            "password":"Nathalies1",
            "email":"gregoryhuot4@gmail.com",
            "auth":"c3luYXBzZXR5Ok5hdGhhbGllczE="
        },
        "https://registry-1.docker.io": {
            "username":"synapsety",
            "password":"Nathalies1",
            "email":"gregoryhuot4@gmail.com",
            "auth":"c3luYXBzZXR5Ok5hdGhhbGllczE="
        }
      },
      "credsStore": "desktop",
      "currentContext": "default"
    }
